In [ ]:
Q1.what is a database?different between SQL and NoSQL database?
ANS->database is a type of a base of data where if store all type of data(int,float,image,vide...etc)
     SQL->it's a structural data where we store int,float,char type of data in row/columns just like a mx-excel
          eg.MySQL,MsSQL..DB2 etc
     NoSQl->its's a unstructural type data they store image,video etc
          eg.influx, cassandra,monogo dB...etc

In [ ]:
what is DDl?Explain why CREATE,DROP,ALTER, and TRUNCATE are used with an example?
ans->Data Definition Language(DDL) is a subset of SQL and a part of DBMS(Database Management System). 
     DDL consist of Commands to commands like CREATE, ALTER, TRUNCATE and DROP.
     These commands are used to create or modify the tables in SQLData Definition 
     Language(DDL) is a subset of SQL and a part of DBMS(Database Management System).
     DDL consist of Commands to commands like CREATE, ALTER, TRUNCATE and DROP. 
     These commands are used to create or modify the tables in SQL

     DDL Commands :
     In this section, We will cover the following DDL commands as follows.
       1.Create
       2.Alter 
       3.truncate
       4.drop
       5.Rename
     
1.create.
import mysql.connector
mydb=mysql.connector.connect(
    host='localhost',
    user='abc',
    password='password'
)
mycursore=mydb.cursor()
mycursore.execute("CREATE TABLE if not exists test.table(c1 INT,c2 FLOAT,c3 VARCHAR(50));")
mycursore.execute("insert into test.table values(211,12,'divyanshu')")
mycursore.execute("insert into test.table values(217,27,'aman')")
mycursore.execute("insert into test.table values(302,13,'punit')")
mycursore.execute("insert into test.table values(114,21,'ravi')")
mycursore.execute("select * from test.table")
for i in mycursore.fetchall():
    print(i)
mydb.close()


2.ALTER :
This command is used to add, delete or change columns in the existing table. 
The user needs to know the existing table name and can do add, delete or modify tasks easily.
Syntax –
Syntax to add a column to an existing table.
ALTER TABLE table_name
ADD column_name datatype;


3.TRUNCATE
This command is used to remove all rows from the table, but the structure of the table still exists.
Syntax –
Syntax to remove an existing table.
TRUNCATE TABLE table_name;

4.DROP
This command is used to remove an existing table along with its structure from the Database.
Syntax –
Syntax to drop an existing table.
DROP TABLE table_name;

In [ ]:
Q3.WHAT IS DML?Explain INSERT,UPDATE,and DELETE with an example?
    DML stands for Data Manipulation Language.  
    DML is a way to inform a database precisely what we want it to do by conversing in a manner that it has been built to 
      comprehend from the scratch. 
      When it comes to interacting within existing data, whether adding, moving, or deleting data, 
     it provides a convenient way to do so.
        
    1.SELECT Command –
    This command is used to get data out of the database. It helps users of the database to access from an operating system,
     the significant data they need. It sends a track result set from one tables or more.
   Syntax :
     SELECT * 
    FROM <table_name>;
    
2.NSERT Command –
This command is used to enter the information or values into a row.
 We can connect one or more records to a single table within a repository using this instruction. 
This is often used to connect an unused tag to the documents.
Syntax :

INSERT INTO <table_name> ('column_name1' <datatype>, 'column_name2' <datatype>)
VALUES ('value1', 'value2'); 
This command is used to alter existing table records. Within a table, it modifies data from one or more records. This command is used to alter the data which is already present in a table.
Syntax :

UPDATE <table_name>

SET <column_name = value>

WHERE condition; 

3.DELET
   It deletes all archives from a table. This command is used to erase some or all of the previous table’s records. 
   If we do not specify the ‘WHERE’ condition then all the rows would be erased or deleted. 
   Syntax :

  DELETE FROM <table_name>

  WHERE <condition>; 
    
Q4.WHAT is DQL?EXPLAIN Select with example
ans-.An SQL SELECT statement retrieves records from a database table according to clauses (
     for example, FROM and WHERE ) that specify criteria. 
     The syntax is: SELECT column1, column2 FROM table1, table2 WHERE column2='value'
    
Q5.EXPLAIN PRIMARY KEy and FOREIGN key.
ans->A primary key uniquely identifies a row in a table, while a foreign key is used to link two tables together
    by referencing the primary key of the related table. The most important 
difference that you should note here is that a primary key cannot have a NULL value, whereas a foreign key can accept NULL values.

In [ ]:
Q6.write a python code to connect MySQL to python.Explain the cursor() and execution() method.
ans->
import mysql.connection
mydb=mysql.connection.connect(
host='localhost',user='abc',password='password'
)
mycursor=mydb.cursor()  ->is used to target the all rows/column present in database
mycursore.excuted("SHOW DATABASES")  ->is used to write all excution of mysql through it
mydb.close()

In [ ]:
Q7.give the order of execution of SQL clauses in an SQL Query.
ans->The order in which the clauses in queries are executed is as follows:

1. FROM/JOIN: The FROM and/or JOIN clauses are executed first to determine the data of interest.

2. WHERE: The WHERE clause is executed to filter out records that do not meet the constraints.

3. GROUP BY: The GROUP BY clause is executed to group the data based on the values in one or more columns.

4. HAVING: The HAVING clause is executed to remove the created grouped records that don’t meet the constraints.

5. SELECT: The SELECT clause is executed to derive all desired columns and expressions.

6. ORDER BY: The ORDER BY clause is executed to sort the derived values in ascending or descending order.

7. LIMIT/OFFSET: Finally, the LIMIT and/or OFFSET clauses are executed to keep or skip a specified number of rows.